### ISSUE TITLE
Time slider - Create a time slider for a layer type to display layers from different years

### ISSUE THREAD

**Issue by Vismayak** [geostreams/gltg#35]

**Comment by max-zilla** [comment]
Suggest we use Hypoxia Contours as example: https://github.com/geostreams/gltg/blob/develop/config.json#L189

We need a new config structure that allows the sidebar to display these as one entry with a year dropdown.  

![Image](https://github.com/geostreams/gltg/assets/14166971/b15f341b-86dd-4219-ba85-00e0b6209577)

Maybe config could be something like...


```
"Hypoxia and Precipitation":[
                {
                    "title":"Hypoxia Contours",
                    "time_entries": [
{"year": 2005, "id": "gltg:2005_Hypoxia_Contours", "legend": "..." }
]}
```
