### ISSUE TITLE
Revise trends dashboard legend icons & new top bar for filtering

### ISSUE THREAD

**Issue by max-zilla** [geostreams/gltg#88]
![image](https://github.com/geostreams/gltg/assets/16596733/007cbff7-319d-4e6c-84f4-efbc43d7678e)

**Comment by Vismayak** [comment]
- [x] Create new icons and update them in map, legend and side bar
- [x] Make time period option a floating div
- [ ] Create three columns for overview, Nitrate and Phopshorous
- [ ] #103 Rearrange graphs
